name: CI

permissions: {}

on:
# push:             # รันอัตโนมัติทุกครั้งที่มีการ Push code ขึ้น GitHub
#   pull_request:     # รันอัตโนมัติเมื่อมีการเปิด Pull Request
  workflow_dispatch: # เปิดปุ่มให้กดรันเองได้แบบ Manual

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Run Forge build
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv
